Stat svc
kasisaki/java-explore-with-me pull request #3
Opened 2023-07-19 23:43 UTC by kasisaki

2023-07-22 15:33 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, давай мелочи поправим и зачет будет =)

2023-07-22 15:33 UTC, krylov-sergey-sergeevich commented on pom.xml
> +				<artifactId>hibernate-core</artifactId>
А мы прям с чистым хибером напрямую будем работать?

2023-07-22 15:33 UTC, krylov-sergey-sergeevich commented on stats-service/stats-server/src/main/java/ru/practicum/statsServer/controller/StatController.java
> +            @RequestParam(name = "start") @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
"yyyy-MM-dd HH:mm:ss" - повторяется много где, давай в константы вынесем

2023-07-22 15:33 UTC, krylov-sergey-sergeevich commented on stats-service/stats-server/src/main/resources/schema.sql
Не обязательно исправлять, но можно еще так (можно иметь ввиду):
```
CREATE TABLE IF NOT EXISTS apps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(150) NOT NULL,
  CONSTRAINT pk_aps PRIMARY KEY (id),
  CONSTRAINT UQ_APPS_NAME UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS endpoint_hit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app_id BIGINT NOT NULL,
  uri VARCHAR(2048),
  ip VARCHAR(15) NOT NULL,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_endpoint_hit PRIMARY KEY (id),
  CONSTRAINT FK_ENDPOINT_HIT_ON_APP FOREIGN KEY (app_id) REFERENCES apps (id)
);
```

2023-07-22 20:54 UTC, kasisaki commented on pom.xml
> +				<artifactId>hibernate-core</artifactId>
Убрал зависимость, т.к. hibernate будет подтянут как вторичная зависимость

2023-07-22 21:02 UTC, kasisaki commented on stats-service/stats-server/src/main/java/ru/practicum/statsServer/controller/StatController.java
> +            @RequestParam(name = "start") @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
done

2023-07-22 21:23 UTC, kasisaki commented on stats-service/stats-server/src/main/resources/schema.sql
Далее обязательно рассмотрю такой вариант. Пока у меня нет понятия какие apps могут присутствовать в запросах.

2023-07-22 21:37 UTC, merged

2023-07-23 18:50 UTC, krylov-sergey-sergeevich reviewed
Привет, зачет!