main_svc
kasisaki/java-explore-with-me pull request #4
Opened 2023-07-24 00:46 UTC by kasisaki

2023-08-03 18:10 UTC, krylov-sergey-sergeevich requested changes
- Дженерики в методах это штука сложная и опасная, точно они нам нужны?
- Исключения на англ языке

Давай доработаем

2023-08-03 18:10 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/mainService/service/EventService.java
> +        statClient.appendStats(new StatHitDto("ewm-main-service",
"ewm-main-service" - лучше наверно как переменную приложения делать

2023-08-03 18:10 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/mainService/service/EventService.java
> +                LocalDateTime.now().format(DateTimeFormatter.ofPattern(DATE_PATTERN))));
Я рекомендую для таких штук использовать свой класс DateUtils

2023-08-03 18:10 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/mainService/service/EventService.java
> +            throw new BadRequestException("Дата и время на которые намечено событие не может быть раньше, " +
текст исключения лучше на англ

2023-08-03 18:10 UTC, krylov-sergey-sergeevich commented on stats-service/stats-client/pom.xml
> +            <version>4.5.13</version>
Точно нам нужна зависимость?

2023-08-03 19:08 UTC, kasisaki commented on main-service/src/main/java/ru/practicum/mainService/mappers/CategoryMapper.java
> +public class CategoryMapper {
У меня почему-то не подтянулась эта аннотация, хотя версия lombok указана 1.18.28.
Добавил исключение на случай попытки вызова конструктора.

2023-08-03 19:15 UTC, kasisaki commented on main-service/pom.xml
> +            <version>2.10.1</version>
В существующей реализации - нет не нужна. Удалил. Сначала хотел обрабатывать с его помощью данные из StatClient вытаскивать. Реализовал свой вариант.

2023-08-03 19:27 UTC, kasisaki commented on main-service/src/main/java/ru/practicum/mainService/models/Event.java
> +@Data
Добавил собственный toString(), чтобы исключить добавление от Lombok

2023-08-03 19:56 UTC, kasisaki commented on main-service/src/main/java/ru/practicum/mainService/service/EventService.java
> +                LocalDateTime.now().format(DateTimeFormatter.ofPattern(DATE_PATTERN))));
ok

2023-08-03 20:08 UTC, kasisaki commented on main-service/src/main/java/ru/practicum/mainService/service/EventService.java
> +            throw new BadRequestException("Дата и время на которые намечено событие не может быть раньше, " +
++

2023-08-03 21:46 UTC, kasisaki commented on stats-service/stats-client/pom.xml
> +            <version>4.5.13</version>
нет.

2023-08-03 22:09 UTC, kasisaki commented on main-service/src/main/java/ru/practicum/mainService/service/EventService.java
> +        statClient.appendStats(new StatHitDto("ewm-main-service",
перенес в application.yml

2023-08-04 20:45 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-08-04 22:13 UTC, merged